stream:
  data_root: './data'
  output_dir: 'logs'

train:
  seed: 603
  batch_size: 64
  epochs: 10
  ft_lr: 0.0001
  fc_lr: 0.001
  momentum: 0.9
  gamma: 0.1
  step_size: 5
  weight_decay: 0.0001
  beta: 1.0
  save: false

test:
  cnn_path: './model/CNN-CIFAR100.pth'
  vit_path: './model/ViT-CIFAR100.pth'