stream:
  root: './data'

common:
  seed: 610
  batch_size: 64
  num_workers: 2

train:
  byol:
    epochs: 100
    lr: 0.0003
    hidden_dim: 2048
    output_dim: 256
    update_rate: 0.99
    data_type: 'tinyimage'
  resnet:
    epochs: 20
    lr: 0.001
    weight_decay: 0.0001
  linear:
    epochs: 200
    lr: 0.005