stream:
  root: './data'

common:
  seed: 610
  batch_size: 128
  num_workers: 2

train:
  simclr:
    epochs: 120
    lr: 0.0003
    temp: 0.07
    weight_decay: 0.0001
  resnet:
    epochs: 20
    lr: 0.001
    weight_decay: 0.0001
  linear:
    epochs: 500
    lr: 0.005

test:
  path: './model'