stream:
  root: './data'

common:
  seed: 610
  batch_size: 64
  num_workers: 2

train:
  byol:
    epochs: 60
    lr: 0.0003
    hidden_dim: 4096
    output_dim: 200
    update_rate: 0.99
    weight_decay: 0.0001
  resnet:
    epochs: 20
    lr: 0.001
    weight_decay: 0.0001
  linear:
    epochs: 100
    lr: 0.005

test:
  path: './model'