stream:
  root: './data'

common:
  seed: 605
  batch_size: 64
  num_workers: 2

train:
  byol:
    epochs: 40
    lr: 0.003
    hidden_dim: 4096
    output_dim: 256
    update_rate: 0.99
    weight_decay: 0.0001
  resnet:
    epochs: 20
    lr: 0.001
    weight_decay: 0.0001
  linear:
    epochs: 100
    lr: 0.001

test:
  path: './model'